"""
Docstring pendiente para este documento
"""
from django.conf.urls import patterns, url
from widget.views import WidgetListView, WidgetView, WidgetUpdate, WidgetDelete, ConfigurarWidgetView
from widget import views

urlpatterns = patterns('',
                       url(r'^$',
                           WidgetListView.as_view(),
                           name='list_widget'),
                       url(r'^nuevo',
                           WidgetView.as_view(),
                           name='add_widget'),
                       url(r'^editar/(?P<pk>\d+)/$',
                           WidgetUpdate.as_view(),
                           name='edit_widget'),
                       url(r'^eliminar/(?P<pk>\d+)/$',
                           WidgetDelete.as_view(),
                           name='eliminar_widget'),
                       url(r'^configurar/$',
                           ConfigurarWidgetView.as_view(),
                           name='configurar_widget'),
                       url(r'^actualizarVisible/$',
                           views.cambiar_WidgetVisible,
                           name='actualizarVisible'),
                       url(r'^actualizarColumna/$',
                           views.cambiar_WidgetColumna,
                           name='actualizarColumna'),
                       url(r'^actualizarColumna2/$',
                           views.cambiar_WidgetColumna2,
                           name='actualizarColumna2'),
                       url(r'^actualizarColumnaMin/$',
                           views.cambiar_WidgetColumnaMin,
                           name='actualizarColumnaMin'),
                       url(r'^actualizarOrden/$',
                           views.cambiar_WidgetOrden,
                           name='actualizarOrden'),
                       url(r'^actualizarOrden2/$',
                           views.cambiar_WidgetOrden2,
                           name='actualizarOrden2'),
                       url(r'^configurar_WidgetVisible/$',
                           views.configurar_WidgetVisible,
                           name='configurar_WidgetVisible'),
                       url(r'^orden_widgets/$',
                           views.orden_Widgets,
                           name='orden_widgets'),
                       )
