# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('estadoderegistro', '0001_initial'),
        ('servicio', '0003_auto_20160331_1430'),
        ('material', '0003_auto_20160331_1430'),
        ('premisas', '0003_auto_20160301_0825'),
        ('ambiente', '0001_initial'),
        ('cliente', '0004_auto_20160303_1401'),
        ('herramienta', '0001_initial'),
        ('gestiondedocumento', '0001_initial'),
        ('mueble', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(max_digits=9, decimal_places=2)),
                ('monto_cotizacion', models.DecimalField(max_digits=9, decimal_places=2)),
                ('banco', models.CharField(max_length=100, blank=True)),
                ('numero_transaccion', models.CharField(max_length=100, blank=True)),
            ],
            options={
                'verbose_name': 'Concepto de la cotización',
                'verbose_name_plural': 'Conceptos de la cotización',
                'ordering': ['cotizacion', 'usuario_registro'],
            },
        ),
        migrations.CreateModel(
            name='ArgumentoDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('valor', models.DecimalField(max_digits=9, decimal_places=2)),
                ('aplicado', models.BooleanField(default=None)),
            ],
            options={
                'verbose_name': 'Argumento de venta',
                'verbose_name_plural': 'Argumentos de venta',
                'ordering': ['cotizacion', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoDeCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('concepto', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('positivo', models.BooleanField(default=None)),
            ],
            options={
                'verbose_name': 'Concepto de cotización',
                'verbose_name_plural': 'Conceptos de cotizaciones',
                'ordering': ['concepto'],
            },
        ),
        migrations.CreateModel(
            name='ContenedorMueble',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('nombre_contenedor', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Contenedor del mueble',
                'verbose_name_plural': 'Contenedores del mueble',
                'ordering': ['cotizacion_mueble', 'contenedor'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('numero_contrato', models.CharField(max_length=100, blank=True)),
                ('numero_cotizacion', models.CharField(max_length=100)),
                ('nombre_cliente', models.CharField(max_length=300)),
                ('fecha_de_cotizacion', models.DateField(auto_now_add=True)),
                ('hora_de_cotizacion', models.TimeField(auto_now_add=True)),
                ('tiempo_carga', models.DecimalField(max_digits=7, default=0.0, decimal_places=2, blank=True)),
                ('total_recorrido_tiempo', models.DecimalField(max_digits=7, default=0.0, decimal_places=2, blank=True)),
                ('total_recorrido_km', models.DecimalField(max_digits=7, default=0.0, decimal_places=2, blank=True)),
                ('nivel_de_complejidad_riesgo', models.CharField(max_length=25, blank=True)),
                ('porcentaje_complejidad_riesgo', models.DecimalField(max_digits=7, default=6, decimal_places=2)),
                ('cliente', models.ForeignKey(to='cliente.Cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['numero_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('observaciones', models.TextField()),
                ('ambiente', models.ForeignKey(to='ambiente.Ambiente')),
            ],
            options={
                'verbose_name': 'Ambiente de la cotización',
                'verbose_name_plural': 'Ambientes de la cotización',
                'ordering': ['direccion_origen', 'ambiente'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionBitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
                ('usuario_registro', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación de la cotización',
                'verbose_name_plural': 'Observaciones de la cotización',
                'ordering': ['cotizacion', 'observacion'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionComplejidadRiesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('situacion', models.CharField(max_length=100)),
                ('factor_complejidad', models.IntegerField()),
                ('factor_riesgo', models.IntegerField()),
                ('observacion', models.TextField()),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
            ],
            options={
                'verbose_name': 'Situación de la cotización',
                'verbose_name_plural': 'Situaciones de la cotización',
                'ordering': ['cotizacion', 'situacion'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('direccion', models.TextField()),
                ('orden', models.IntegerField()),
                ('nombre_de_edificio', models.CharField(max_length=250)),
                ('tipo_de_edificacion', models.CharField(max_length=100)),
                ('rampa', models.BooleanField(default=None)),
                ('distancia_del_vehiculo', models.IntegerField()),
                ('cantidad_pisos', models.IntegerField()),
                ('pisos_escalera', models.IntegerField()),
                ('escalera_estrecha', models.BooleanField(default=None)),
                ('escalera_inclinada', models.BooleanField(default=None)),
                ('escalon_grande', models.BooleanField(default=None)),
                ('especificacion_de_inmueble', models.CharField(max_length=250)),
                ('numero_de_inmueble', models.IntegerField()),
                ('numero_de_pisos', models.IntegerField()),
                ('nombre_piso', models.CharField(max_length=100)),
                ('cantidad_de_ambientes', models.IntegerField()),
                ('pisos_por_escalera', models.IntegerField()),
                ('numero_de_plantas', models.IntegerField()),
                ('total_m2', models.DecimalField(max_digits=7, decimal_places=2)),
                ('baulera', models.BooleanField(default=None)),
                ('volumen_baulera', models.DecimalField(max_digits=7, decimal_places=2)),
                ('clientedireccion', models.ForeignKey(to='cliente.ClienteDireccion')),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
            ],
            options={
                'verbose_name': 'Dirección de la cotización',
                'verbose_name_plural': 'Direcciones de la cotización',
                'ordering': ['cotizacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('fecha_registro', models.DateField()),
                ('observacion', models.TextField()),
                ('predefinido', models.BooleanField(default=None)),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
                ('estado_de_documento', models.ForeignKey(to='gestiondedocumento.EstadoDeDocumento', blank=True, null=True)),
                ('estado_de_registro', models.ForeignKey(to='estadoderegistro.EstadoDeRegistro', blank=True, null=True)),
                ('usuario_registro', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de la cotización',
                'verbose_name_plural': 'Estados de la cotización',
                'ordering': ['cotizacion', 'usuario_registro'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionHerramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('nombre_herramienta', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(max_digits=7, decimal_places=2)),
                ('descripcion_de_cantidad', models.TextField()),
                ('cantidad_asignada', models.DecimalField(max_digits=7, decimal_places=2)),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
                ('herramienta', models.ForeignKey(to='herramienta.Herramienta')),
            ],
            options={
                'verbose_name': 'Herramienta de la cotización',
                'verbose_name_plural': 'Herramientas de la cotización',
                'ordering': ['cotizacion', 'herramienta'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionHistoricoFecha',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('nombre_tipo_fecha', models.CharField(max_length=100)),
                ('fecha_actual', models.DateField()),
                ('hora_actual', models.TimeField()),
                ('observacion', models.TextField()),
                ('aplicar', models.BooleanField(default=None)),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
            ],
            options={
                'verbose_name': 'Observación de la cotización',
                'verbose_name_plural': 'Observaciones de la cotización',
                'ordering': ['cotizacion', 'tipo_fecha'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('nombre_material', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(max_digits=7, decimal_places=2)),
                ('descripcion_de_cantidad', models.TextField()),
                ('cantidad_asignada', models.DecimalField(max_digits=7, decimal_places=2)),
                ('precio_unitario', models.DecimalField(max_digits=9, decimal_places=2)),
                ('monto_material', models.DecimalField(max_digits=9, decimal_places=2)),
                ('monto_material_asignado', models.DecimalField(max_digits=9, decimal_places=2)),
                ('peso_unitario', models.DecimalField(max_digits=7, decimal_places=2)),
                ('peso_total', models.DecimalField(max_digits=7, decimal_places=2)),
                ('inlcuido', models.BooleanField(default=None)),
                ('basico', models.BooleanField(default=None)),
                ('aplicar', models.BooleanField(default=None)),
                ('observacion', models.TextField()),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
                ('material', models.ForeignKey(to='material.Material')),
            ],
            options={
                'verbose_name': 'Material de la cotización',
                'verbose_name_plural': 'Materiales de la cotización',
                'ordering': ['cotizacion', 'material'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionMueble',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('nombre_especificacion_de_mueble', models.CharField(max_length=100)),
                ('ancho', models.DecimalField(max_digits=7, decimal_places=2)),
                ('largo', models.DecimalField(max_digits=7, decimal_places=2)),
                ('alto', models.DecimalField(max_digits=7, decimal_places=2)),
                ('cantidad', models.IntegerField()),
                ('volumen_en_camion', models.IntegerField()),
                ('trasladable', models.BooleanField(default=None)),
                ('observaciones', models.TextField()),
                ('cotizacion_ambiente', models.ForeignKey(to='cotizacionweb.CotizacionAmbiente')),
                ('direccion_destino', models.ForeignKey(to='cotizacionweb.CotizacionDireccion')),
                ('especificacion_de_mueble', models.ForeignKey(to='mueble.EspecificacionDeMueble')),
            ],
            options={
                'verbose_name': 'Mueble de la cotización',
                'verbose_name_plural': 'Muebles de la cotización',
                'ordering': ['cotizacion_ambiente', 'especificacion_de_mueble'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('nombre_concepto', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(max_digits=7, decimal_places=2)),
                ('precio_unitario', models.DecimalField(max_digits=9, decimal_places=2)),
                ('precio_total', models.DecimalField(max_digits=9, decimal_places=2)),
                ('precio_total_asignado', models.DecimalField(max_digits=9, decimal_places=2)),
                ('descripcion_precio_total', models.TextField()),
                ('concepto', models.ForeignKey(to='cotizacionweb.ConceptoDeCotizacion')),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
                ('unidad_de_medida', models.ForeignKey(to='premisas.Unidad')),
            ],
            options={
                'verbose_name': 'Concepto de la cotización',
                'verbose_name_plural': 'Conceptos de la cotización',
                'ordering': ['cotizacion', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('nombre_de_servicio', models.CharField(max_length=100)),
                ('complejidad_servicio', models.CharField(max_length=100)),
                ('porcentaje_complejidad', models.DecimalField(max_digits=7, decimal_places=2)),
                ('monto_servicio', models.DecimalField(max_digits=9, decimal_places=2)),
                ('descripcion_de_monto_servicio', models.TextField()),
                ('monto_servicio_asignado', models.DecimalField(max_digits=9, decimal_places=2)),
                ('incluido_en_precio', models.BooleanField(default=None)),
                ('aplicar_servicio', models.BooleanField(default=None)),
                ('basico', models.BooleanField(default=None)),
                ('observacion', models.TextField()),
                ('cotizacion', models.ForeignKey(to='cotizacionweb.Cotizacion')),
                ('servicio', models.ForeignKey(to='servicio.Servicio')),
            ],
            options={
                'verbose_name': 'Servicio de la cotización',
                'verbose_name_plural': 'Servicios de la cotización',
                'ordering': ['cotizacion', 'servicio'],
            },
        ),
        migrations.CreateModel(
            name='FechaDeCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('nombre_fecha', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Fecha de cotización',
                'verbose_name_plural': 'Fechas de cotizaciones',
                'ordering': ['nombre_fecha'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMueble',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('descripcion_servicio', models.CharField(max_length=100)),
                ('complejidad_servicio', models.CharField(max_length=100)),
                ('porcentaje_complejidad', models.DecimalField(max_digits=7, decimal_places=2)),
                ('monto_servicio', models.DecimalField(max_digits=9, decimal_places=2)),
                ('descripcion_monto_servicio', models.TextField()),
                ('monto_servicio_asignado', models.DecimalField(max_digits=9, decimal_places=2)),
                ('incluido', models.BooleanField(default=None)),
                ('cotizacion_mueble', models.ForeignKey(to='cotizacionweb.CotizacionMueble')),
                ('servicio', models.ForeignKey(to='servicio.Servicio')),
            ],
            options={
                'verbose_name': 'Servicio del mueble',
                'verbose_name_plural': 'Servicios del mueble',
                'ordering': ['cotizacion_mueble', 'servicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoAbono',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('tipo_abono', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de abono',
                'verbose_name_plural': 'Tipos de abonos',
                'ordering': ['tipo_abono'],
            },
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', serialize=False, primary_key=True)),
                ('tipo_direccion', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de dirección',
                'verbose_name_plural': 'Tipo de direcciones',
                'ordering': ['tipo_direccion'],
            },
        ),
        migrations.AddField(
            model_name='cotizacionhistoricofecha',
            name='tipo_fecha',
            field=models.ForeignKey(to='cotizacionweb.FechaDeCotizacion'),
        ),
        migrations.AddField(
            model_name='cotizacionhistoricofecha',
            name='usuario_registro',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizaciondireccion',
            name='tipo_direccion',
            field=models.ForeignKey(to='cotizacionweb.TipoDireccion'),
        ),
        migrations.AddField(
            model_name='cotizacionambiente',
            name='direccion_origen',
            field=models.ForeignKey(to='cotizacionweb.CotizacionDireccion'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='como_abona',
            field=models.ForeignKey(to='cotizacionweb.TipoAbono'),
        ),
    ]
