-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.67.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06-05-2016 02:41:40 p.m.
-- Source server version: 5.6.21
-- Source connection string: User Id=root;Host=localhost;Character Set=utf8;
-- Target server version: 5.6.21
-- Target connection string: User Id=root;Host=localhost;Character Set=utf8;
-- Run this script against db_mtvmcotizacionv2_prd to synchronize it with db_mtvmcotizacionv2
-- Please backup your target database before running this script

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';
USE db_mtvmcotizacionv2;

--
-- Alter table herramienta_herramienta
--
ALTER TABLE herramienta_herramienta
  DROP FOREIGN KEY herramienta_herramienta_unidad_id_272edb2_fk_almacen_unidad_id;
ALTER TABLE herramienta_herramienta
  ADD CONSTRAINT herramienta_herramienta_unidad_id_272edb2_fk_almacen_unidad_id FOREIGN KEY (unidad_id)
    REFERENCES almacen_unidad(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table material_material
--
ALTER TABLE material_material
  DROP FOREIGN KEY material_mate_unidad_de_consumo_id_1c639de1_fk_almacen_unidad_id;
ALTER TABLE material_material
  ADD CONSTRAINT material_mate_unidad_de_consumo_id_1c639de1_fk_almacen_unidad_id FOREIGN KEY (unidad_de_consumo_id)
    REFERENCES almacen_unidad(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE material_material
  DROP FOREIGN KEY material_materi_unidad_de_venta_id_513cb613_fk_almacen_unidad_id;
ALTER TABLE material_material
  ADD CONSTRAINT material_materi_unidad_de_venta_id_513cb613_fk_almacen_unidad_id FOREIGN KEY (unidad_de_venta_id)
    REFERENCES almacen_unidad(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Create table notificacion_notificacion
--
CREATE TABLE notificacion_notificacion (
  id INT(11) NOT NULL AUTO_INCREMENT,
  origen VARCHAR(100) NOT NULL,
  titulo VARCHAR(250) NOT NULL,
  texto LONGTEXT NOT NULL,
  estado VARCHAR(100) NOT NULL,
  fecha_entrega DATETIME NOT NULL,
  fecha_alerta DATETIME NOT NULL,
  log LONGTEXT NOT NULL,
  url VARCHAR(500) NOT NULL,
  fecha_creacion DATETIME NOT NULL,
  user_id INT(11) NOT NULL,
  user_origen_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  INDEX notificacion_notificacion_user_id_606599be_fk_auth_user_id (user_id),
  INDEX notificacion_notificacion_user_origen_id_25d8929_fk_auth_user_id (user_origen_id),
  CONSTRAINT notificacion_notificacion_user_id_606599be_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT notificacion_notificacion_user_origen_id_25d8929_fk_auth_user_id FOREIGN KEY (user_origen_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Alter table servicio_servicio
--
ALTER TABLE servicio_servicio
  DROP FOREIGN KEY servicio_serv_unidad_de_consumo_id_334a1b70_fk_almacen_unidad_id;
ALTER TABLE servicio_servicio
  ADD CONSTRAINT servicio_serv_unidad_de_consumo_id_334a1b70_fk_almacen_unidad_id FOREIGN KEY (unidad_de_consumo_id)
    REFERENCES almacen_unidad(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE servicio_servicio
  DROP FOREIGN KEY servicio_servic_unidad_de_venta_id_41fb160a_fk_almacen_unidad_id;
ALTER TABLE servicio_servicio
  ADD CONSTRAINT servicio_servic_unidad_de_venta_id_41fb160a_fk_almacen_unidad_id FOREIGN KEY (unidad_de_venta_id)
    REFERENCES almacen_unidad(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Create table notificacion_notificacionestado
--
CREATE TABLE notificacion_notificacionestado (
  id INT(11) NOT NULL AUTO_INCREMENT,
  fecha_registro DATETIME NOT NULL,
  observacion LONGTEXT NOT NULL,
  predefinido TINYINT(1) NOT NULL,
  estado_de_documento_id INT(11) NOT NULL,
  notificacion_id INT(11) NOT NULL,
  usuario_registro_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  INDEX efd5337550a5ee391c7661343b9a0674 (estado_de_documento_id),
  INDEX notific_notificacion_id_7fc5a102_fk_notificacion_notificacion_id (notificacion_id),
  INDEX notificacion_notifi_usuario_registro_id_6b4e2ef2_fk_auth_user_id (usuario_registro_id),
  CONSTRAINT efd5337550a5ee391c7661343b9a0674 FOREIGN KEY (estado_de_documento_id)
    REFERENCES gestiondedocumento_estadodedocumento(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT notific_notificacion_id_7fc5a102_fk_notificacion_notificacion_id FOREIGN KEY (notificacion_id)
    REFERENCES notificacion_notificacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT notificacion_notifi_usuario_registro_id_6b4e2ef2_fk_auth_user_id FOREIGN KEY (usuario_registro_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Alter table contenedor_contenedortipicopormueble
--
ALTER TABLE contenedor_contenedortipicopormueble
  DROP FOREIGN KEY c_tipo_de_contenido_id_29692e5f_fk_contenedor_tipodecontenido_id;
ALTER TABLE contenedor_contenedortipicopormueble
  ADD CONSTRAINT c_tipo_de_contenido_id_29692e5f_fk_contenedor_tipodecontenido_id FOREIGN KEY (tipo_de_contenido_id)
    REFERENCES contenedor_tipodecontenido(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacion
--
ALTER TABLE cotizacionweb_cotizacion
  CHANGE COLUMN hora_de_cotizacion hora_de_cotizacion TIME NOT NULL;

ALTER TABLE cotizacionweb_cotizacion
  DROP FOREIGN KEY cotizacionw_como_abona_id_2d98d780_fk_cotizacionweb_tipoabono_id;
ALTER TABLE cotizacionweb_cotizacion
  ADD CONSTRAINT cotizacionw_como_abona_id_2d98d780_fk_cotizacionweb_tipoabono_id FOREIGN KEY (como_abona_id)
    REFERENCES cotizacionweb_tipoabono(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacion
  DROP FOREIGN KEY cotizacionweb_co_cotizador_id_2b7fef0f_fk_cotizador_cotizador_id;
ALTER TABLE cotizacionweb_cotizacion
  ADD CONSTRAINT cotizacionweb_co_cotizador_id_2b7fef0f_fk_cotizador_cotizador_id FOREIGN KEY (cotizador_id)
    REFERENCES cotizador_cotizador(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacion
  DROP FOREIGN KEY cotizacionweb_cotizaci_cliente_id_666eca08_fk_cliente_cliente_id;
ALTER TABLE cotizacionweb_cotizacion
  ADD CONSTRAINT cotizacionweb_cotizaci_cliente_id_666eca08_fk_cliente_cliente_id FOREIGN KEY (cliente_id)
    REFERENCES cliente_cliente(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_abono
--
ALTER TABLE cotizacionweb_abono
  CHANGE COLUMN hora_registro hora_registro TIME NOT NULL;

ALTER TABLE cotizacionweb_abono
  DROP FOREIGN KEY cotizacion_cotizacion_id_15c9bd6b_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_abono
  ADD CONSTRAINT cotizacion_cotizacion_id_15c9bd6b_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_abono
  DROP FOREIGN KEY cotizacionw_tipo_abono_id_72503b5e_fk_cotizacionweb_tipoabono_id;
ALTER TABLE cotizacionweb_abono
  ADD CONSTRAINT cotizacionw_tipo_abono_id_72503b5e_fk_cotizacionweb_tipoabono_id FOREIGN KEY (tipo_abono_id)
    REFERENCES cotizacionweb_tipoabono(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_abono
  DROP FOREIGN KEY cotizacionweb_abono_usuario_registro_id_5f7cc074_fk_auth_user_id;
ALTER TABLE cotizacionweb_abono
  ADD CONSTRAINT cotizacionweb_abono_usuario_registro_id_5f7cc074_fk_auth_user_id FOREIGN KEY (usuario_registro_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_argumentodeventa
--
ALTER TABLE cotizacionweb_argumentodeventa
  DROP FOREIGN KEY cotizacionw_cotizacion_id_943dedc_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_argumentodeventa
  ADD CONSTRAINT cotizacionw_cotizacion_id_943dedc_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionbitacora
--
ALTER TABLE cotizacionweb_cotizacionbitacora
  CHANGE COLUMN hora_registro hora_registro TIME NOT NULL;

ALTER TABLE cotizacionweb_cotizacionbitacora
  DROP FOREIGN KEY cotizacion_cotizacion_id_5e1a934a_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizacionbitacora
  ADD CONSTRAINT cotizacion_cotizacion_id_5e1a934a_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionbitacora
  DROP FOREIGN KEY cotizacionweb_cotiz_usuario_registro_id_556f26a1_fk_auth_user_id;
ALTER TABLE cotizacionweb_cotizacionbitacora
  ADD CONSTRAINT cotizacionweb_cotiz_usuario_registro_id_556f26a1_fk_auth_user_id FOREIGN KEY (usuario_registro_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacioncomplejidadriesgo
--
ALTER TABLE cotizacionweb_cotizacioncomplejidadriesgo
  DROP FOREIGN KEY cotizacion_cotizacion_id_67973ce4_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizacioncomplejidadriesgo
  ADD CONSTRAINT cotizacion_cotizacion_id_67973ce4_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionestado
--
ALTER TABLE cotizacionweb_cotizacionestado
  CHANGE COLUMN fecha_registro fecha_registro DATETIME NOT NULL;

ALTER TABLE cotizacionweb_cotizacionestado
  DROP FOREIGN KEY ace6965b1bb6487bc2291914a281beea;
ALTER TABLE cotizacionweb_cotizacionestado
  ADD CONSTRAINT ace6965b1bb6487bc2291914a281beea FOREIGN KEY (estado_de_documento_id)
    REFERENCES gestiondedocumento_estadodedocumento(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionestado
  DROP FOREIGN KEY cotizacion_cotizacion_id_4b862875_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizacionestado
  ADD CONSTRAINT cotizacion_cotizacion_id_4b862875_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionestado
  DROP FOREIGN KEY cotizacionweb_cotiz_usuario_registro_id_5ce6b26c_fk_auth_user_id;
ALTER TABLE cotizacionweb_cotizacionestado
  ADD CONSTRAINT cotizacionweb_cotiz_usuario_registro_id_5ce6b26c_fk_auth_user_id FOREIGN KEY (usuario_registro_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionestado
  DROP FOREIGN KEY e0745648b4a35fef40096a62e648eaeb;
ALTER TABLE cotizacionweb_cotizacionestado
  ADD CONSTRAINT e0745648b4a35fef40096a62e648eaeb FOREIGN KEY (estado_de_registro_id)
    REFERENCES estadoderegistro_estadoderegistro(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionherramienta
--
ALTER TABLE cotizacionweb_cotizacionherramienta
  DROP FOREIGN KEY cotizacion_herramienta_id_57af3462_fk_herramienta_herramienta_id;
ALTER TABLE cotizacionweb_cotizacionherramienta
  ADD CONSTRAINT cotizacion_herramienta_id_57af3462_fk_herramienta_herramienta_id FOREIGN KEY (herramienta_id)
    REFERENCES herramienta_herramienta(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionherramienta
  DROP FOREIGN KEY cotizacionw_cotizacion_id_59ed8fc_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizacionherramienta
  ADD CONSTRAINT cotizacionw_cotizacion_id_59ed8fc_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionhistoricofecha
--
ALTER TABLE cotizacionweb_cotizacionhistoricofecha
  CHANGE COLUMN fecha fecha DATETIME NOT NULL;

ALTER TABLE cotizacionweb_cotizacionhistoricofecha
  DROP FOREIGN KEY cot_tipo_fecha_id_5a703083_fk_cotizacionweb_fechadecotizacion_id;
ALTER TABLE cotizacionweb_cotizacionhistoricofecha
  ADD CONSTRAINT cot_tipo_fecha_id_5a703083_fk_cotizacionweb_fechadecotizacion_id FOREIGN KEY (tipo_fecha_id)
    REFERENCES cotizacionweb_fechadecotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionhistoricofecha
  DROP FOREIGN KEY cotizacion_cotizacion_id_19699f72_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizacionhistoricofecha
  ADD CONSTRAINT cotizacion_cotizacion_id_19699f72_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionhistoricofecha
  DROP FOREIGN KEY cotizacionweb_cotiz_usuario_registro_id_2e44a585_fk_auth_user_id;
ALTER TABLE cotizacionweb_cotizacionhistoricofecha
  ADD CONSTRAINT cotizacionweb_cotiz_usuario_registro_id_2e44a585_fk_auth_user_id FOREIGN KEY (usuario_registro_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionmaterial
--
ALTER TABLE cotizacionweb_cotizacionmaterial
  DROP FOREIGN KEY cotizacion_cotizacion_id_7414ece4_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizacionmaterial
  ADD CONSTRAINT cotizacion_cotizacion_id_7414ece4_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionmaterial
  DROP FOREIGN KEY cotizacionweb_cotiz_material_id_7d423cc2_fk_material_material_id;
ALTER TABLE cotizacionweb_cotizacionmaterial
  ADD CONSTRAINT cotizacionweb_cotiz_material_id_7d423cc2_fk_material_material_id FOREIGN KEY (material_id)
    REFERENCES material_material(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionpresupuesto
--
ALTER TABLE cotizacionweb_cotizacionpresupuesto
  DROP FOREIGN KEY co_concepto_id_61830244_fk_cotizacionweb_conceptodecotizacion_id;
ALTER TABLE cotizacionweb_cotizacionpresupuesto
  ADD CONSTRAINT co_concepto_id_61830244_fk_cotizacionweb_conceptodecotizacion_id FOREIGN KEY (concepto_id)
    REFERENCES cotizacionweb_conceptodecotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionpresupuesto
  DROP FOREIGN KEY cotizacion_cotizacion_id_25240d8b_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizacionpresupuesto
  ADD CONSTRAINT cotizacion_cotizacion_id_25240d8b_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionpresupuesto
  DROP FOREIGN KEY cotizacionweb__unidad_de_medida_id_2440215b_fk_almacen_unidad_id;
ALTER TABLE cotizacionweb_cotizacionpresupuesto
  ADD CONSTRAINT cotizacionweb__unidad_de_medida_id_2440215b_fk_almacen_unidad_id FOREIGN KEY (unidad_de_medida_id)
    REFERENCES almacen_unidad(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionservicio
--
ALTER TABLE cotizacionweb_cotizacionservicio
  DROP FOREIGN KEY cotizacion_cotizacion_id_11643b24_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizacionservicio
  ADD CONSTRAINT cotizacion_cotizacion_id_11643b24_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionservicio
  DROP FOREIGN KEY cotizacionweb_cotizac_servicio_id_67cfe7_fk_servicio_servicio_id;
ALTER TABLE cotizacionweb_cotizacionservicio
  ADD CONSTRAINT cotizacionweb_cotizac_servicio_id_67cfe7_fk_servicio_servicio_id FOREIGN KEY (servicio_id)
    REFERENCES servicio_servicio(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizaciondireccion
--
ALTER TABLE cotizacionweb_cotizaciondireccion
  DROP FOREIGN KEY cot_tipo_direccion_id_638481ad_fk_cotizacionweb_tipodireccion_id;
ALTER TABLE cotizacionweb_cotizaciondireccion
  ADD CONSTRAINT cot_tipo_direccion_id_638481ad_fk_cotizacionweb_tipodireccion_id FOREIGN KEY (tipo_direccion_id)
    REFERENCES cotizacionweb_tipodireccion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizaciondireccion
  DROP FOREIGN KEY coti_clientedireccion_id_79150be3_fk_cliente_clientedireccion_id;
ALTER TABLE cotizacionweb_cotizaciondireccion
  ADD CONSTRAINT coti_clientedireccion_id_79150be3_fk_cliente_clientedireccion_id FOREIGN KEY (clientedireccion_id)
    REFERENCES cliente_clientedireccion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizaciondireccion
  DROP FOREIGN KEY cotizacionw_cotizacion_id_933f1ff_fk_cotizacionweb_cotizacion_id;
ALTER TABLE cotizacionweb_cotizaciondireccion
  ADD CONSTRAINT cotizacionw_cotizacion_id_933f1ff_fk_cotizacionweb_cotizacion_id FOREIGN KEY (cotizacion_id)
    REFERENCES cotizacionweb_cotizacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionambiente
--
ALTER TABLE cotizacionweb_cotizacionambiente
  DROP FOREIGN KEY cotizacionweb_cotiz_ambiente_id_3ae16d07_fk_ambiente_ambiente_id;
ALTER TABLE cotizacionweb_cotizacionambiente
  ADD CONSTRAINT cotizacionweb_cotiz_ambiente_id_3ae16d07_fk_ambiente_ambiente_id FOREIGN KEY (ambiente_id)
    REFERENCES ambiente_ambiente(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionambiente
  DROP FOREIGN KEY f2802a01778778411a3d1cad076278a1;
ALTER TABLE cotizacionweb_cotizacionambiente
  ADD CONSTRAINT f2802a01778778411a3d1cad076278a1 FOREIGN KEY (direccion_origen_id)
    REFERENCES cotizacionweb_cotizaciondireccion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_cotizacionmueble
--
ALTER TABLE cotizacionweb_cotizacionmueble
  DROP FOREIGN KEY D11febba5d67d7fc23bc5817c199d7ed;
ALTER TABLE cotizacionweb_cotizacionmueble
  ADD CONSTRAINT D11febba5d67d7fc23bc5817c199d7ed FOREIGN KEY (direccion_destino_id)
    REFERENCES cotizacionweb_cotizaciondireccion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionmueble
  DROP FOREIGN KEY D95cd2ce0b4477fb0d3370badefb1779;
ALTER TABLE cotizacionweb_cotizacionmueble
  ADD CONSTRAINT D95cd2ce0b4477fb0d3370badefb1779 FOREIGN KEY (cotizacion_ambiente_id)
    REFERENCES cotizacionweb_cotizacionambiente(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_cotizacionmueble
  DROP FOREIGN KEY ffd1f2bdc910a4d639dbef5a7ee13781;
ALTER TABLE cotizacionweb_cotizacionmueble
  ADD CONSTRAINT ffd1f2bdc910a4d639dbef5a7ee13781 FOREIGN KEY (especificacion_de_mueble_id)
    REFERENCES mueble_especificaciondemueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_contenedormueble
--
ALTER TABLE cotizacionweb_contenedormueble
  DROP FOREIGN KEY co_tipo_de_contenido_id_2a19fcd_fk_contenedor_tipodecontenido_id;
ALTER TABLE cotizacionweb_contenedormueble
  ADD CONSTRAINT co_tipo_de_contenido_id_2a19fcd_fk_contenedor_tipodecontenido_id FOREIGN KEY (tipo_de_contenido_id)
    REFERENCES contenedor_tipodecontenido(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_contenedormueble
  DROP FOREIGN KEY cotizacionweb_contenedor_id_30b38ea8_fk_contenedor_contenedor_id;
ALTER TABLE cotizacionweb_contenedormueble
  ADD CONSTRAINT cotizacionweb_contenedor_id_30b38ea8_fk_contenedor_contenedor_id FOREIGN KEY (contenedor_id)
    REFERENCES contenedor_contenedor(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_contenedormueble
  DROP FOREIGN KEY D2ccfd9b63e1a06a74a0f3e32d7460ff;
ALTER TABLE cotizacionweb_contenedormueble
  ADD CONSTRAINT D2ccfd9b63e1a06a74a0f3e32d7460ff FOREIGN KEY (cotizacion_mueble_id)
    REFERENCES cotizacionweb_cotizacionmueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cotizacionweb_serviciomueble
--
ALTER TABLE cotizacionweb_serviciomueble
  DROP FOREIGN KEY cotizacionweb_servi_servicio_id_44c35488_fk_servicio_servicio_id;
ALTER TABLE cotizacionweb_serviciomueble
  ADD CONSTRAINT cotizacionweb_servi_servicio_id_44c35488_fk_servicio_servicio_id FOREIGN KEY (servicio_id)
    REFERENCES servicio_servicio(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cotizacionweb_serviciomueble
  DROP FOREIGN KEY fc55ccae093057d028d502e4c95cf24e;
ALTER TABLE cotizacionweb_serviciomueble
  ADD CONSTRAINT fc55ccae093057d028d502e4c95cf24e FOREIGN KEY (cotizacion_mueble_id)
    REFERENCES cotizacionweb_cotizacionmueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Enable foreign keys
--

--
-- Inserting data into table auth_permission
--
INSERT INTO auth_permission(id, name, content_type_id, codename) VALUES
(349, 'Can add Notificación', 117, 'add_notificacion'),
(350, 'Can change Notificación', 117, 'change_notificacion'),
(351, 'Can delete Notificación', 117, 'delete_notificacion'),
(352, 'Can add Estado de la notificación', 118, 'add_notificacionestado'),
(353, 'Can change Estado de la notificación', 118, 'change_notificacionestado'),
(354, 'Can delete Estado de la notificación', 118, 'delete_notificacionestado');

--
-- Inserting data into table django_content_type
--
INSERT INTO django_content_type(id, app_label, model) VALUES
(117, 'notificacion', 'notificacion'),
(118, 'notificacion', 'notificacionestado');

--
-- Updating data of table django_migrations
--
UPDATE django_migrations SET applied = '2016-02-04 19:20:53' WHERE id = 25;
UPDATE django_migrations SET applied = '2016-02-04 19:23:15' WHERE id = 26;
UPDATE django_migrations SET applied = '2016-02-12 13:41:18' WHERE id = 27;
UPDATE django_migrations SET applied = '2016-02-15 19:30:54' WHERE id = 28;
UPDATE django_migrations SET applied = '2016-02-15 19:30:59' WHERE id = 29;
UPDATE django_migrations SET applied = '2016-02-15 19:31:17' WHERE id = 30;
UPDATE django_migrations SET applied = '2016-02-15 19:31:23' WHERE id = 31;
UPDATE django_migrations SET applied = '2016-02-15 19:31:32' WHERE id = 32;
UPDATE django_migrations SET applied = '2016-02-15 19:31:49' WHERE id = 33;
UPDATE django_migrations SET applied = '2016-02-17 19:29:15' WHERE id = 34;
UPDATE django_migrations SET applied = '2016-02-17 19:29:20' WHERE id = 35;
UPDATE django_migrations SET applied = '2016-03-01 12:58:37' WHERE id = 36;
UPDATE django_migrations SET applied = '2016-03-01 12:58:38' WHERE id = 37;
UPDATE django_migrations SET applied = '2016-03-01 12:58:38' WHERE id = 38;
UPDATE django_migrations SET applied = '2016-03-01 21:04:28' WHERE id = 39;
UPDATE django_migrations SET applied = '2016-03-01 21:04:31' WHERE id = 40;
UPDATE django_migrations SET applied = '2016-03-02 18:05:31' WHERE id = 41;
UPDATE django_migrations SET applied = '2016-03-02 18:05:32' WHERE id = 42;
UPDATE django_migrations SET applied = '2016-03-03 18:31:53' WHERE id = 43;
UPDATE django_migrations SET applied = '2016-03-03 18:31:59' WHERE id = 44;
UPDATE django_migrations SET applied = '2016-03-03 18:33:16' WHERE id = 45;
UPDATE django_migrations SET applied = '2016-03-04 20:32:37' WHERE id = 46;
UPDATE django_migrations SET applied = '2016-03-14 19:29:32' WHERE id = 47;
UPDATE django_migrations SET applied = '2016-03-14 19:33:38' WHERE id = 48;
UPDATE django_migrations SET applied = '2016-03-18 18:33:56' WHERE id = 49;
UPDATE django_migrations SET applied = '2016-03-31 19:02:07' WHERE id = 51;
UPDATE django_migrations SET applied = '2016-03-31 19:02:09' WHERE id = 52;
UPDATE django_migrations SET applied = '2016-03-31 19:02:11' WHERE id = 53;
UPDATE django_migrations SET applied = '2016-03-31 19:02:12' WHERE id = 54;
UPDATE django_migrations SET applied = '2016-03-31 19:02:14' WHERE id = 55;
UPDATE django_migrations SET applied = '2016-03-31 19:02:19' WHERE id = 56;
UPDATE django_migrations SET applied = '2016-03-31 19:05:16' WHERE id = 57;
UPDATE django_migrations SET applied = '2016-04-01 16:36:46' WHERE id = 61;
UPDATE django_migrations SET applied = '2016-04-04 20:47:07' WHERE id = 63;
UPDATE django_migrations SET applied = '2016-04-08 20:05:10' WHERE id = 64;
UPDATE django_migrations SET applied = '2016-04-08 20:06:17' WHERE id = 65;
UPDATE django_migrations SET applied = '2016-04-08 20:06:19' WHERE id = 66;
UPDATE django_migrations SET applied = '2016-04-08 20:13:06' WHERE id = 67;
UPDATE django_migrations SET applied = '2016-04-08 20:13:09' WHERE id = 68;
UPDATE django_migrations SET applied = '2016-04-08 20:13:12' WHERE id = 69;
UPDATE django_migrations SET applied = '2016-04-08 20:18:24' WHERE id = 70;
UPDATE django_migrations SET applied = '2016-04-08 20:18:25' WHERE id = 71;
UPDATE django_migrations SET applied = '2016-04-08 20:19:22' WHERE id = 72;
UPDATE django_migrations SET applied = '2016-04-11 14:13:30' WHERE id = 73;
UPDATE django_migrations SET applied = '2016-04-11 14:13:32' WHERE id = 74;
UPDATE django_migrations SET applied = '2016-04-12 15:37:18' WHERE id = 75;
UPDATE django_migrations SET applied = '2016-04-12 15:37:20' WHERE id = 76;
UPDATE django_migrations SET applied = '2016-04-14 20:00:12' WHERE id = 77;
UPDATE django_migrations SET applied = '2016-04-14 20:00:13' WHERE id = 78;
UPDATE django_migrations SET applied = '2016-04-14 20:14:40' WHERE id = 79;
UPDATE django_migrations SET applied = '2016-04-18 17:55:38' WHERE id = 80;
UPDATE django_migrations SET applied = '2016-04-18 17:55:39' WHERE id = 81;
UPDATE django_migrations SET applied = '2016-04-18 17:55:43' WHERE id = 82;
UPDATE django_migrations SET applied = '2016-04-18 17:58:46' WHERE id = 83;
UPDATE django_migrations SET applied = '2016-04-20 15:39:04' WHERE id = 84;
UPDATE django_migrations SET applied = '2016-04-20 16:18:18' WHERE id = 85;
UPDATE django_migrations SET applied = '2016-04-22 12:55:49' WHERE id = 86;

--
-- Inserting data into table django_migrations
--
INSERT INTO django_migrations(id, app, name, applied) VALUES
(87, 'vehiculo', '0003_auto_20160429_1614', '2016-04-29 20:44:44'),
(88, 'notificacion', '0001_initial', '2016-05-06 15:06:27');

--
-- Inserting data into table gestiondedocumento_estadodedocumento
--
INSERT INTO gestiondedocumento_estadodedocumento(id, estado_de_documento, descripcion, orden, observacion, tipo_de_documento_id) VALUES
(24, 'Por entregar', 'Es cuando la notificación es creada', 1, ' ', 4),
(25, 'Entregada', 'Es el estado que se asigna cuando se envía la notificación al usuario', 2, ' ', 4),
(26, 'No leída', 'Es el estado que se asigna al recibir la notificación', 3, ' ', 4),
(27, 'Leída', 'Es el estado que se asigna cuando el usuario lee la notificación', 4, ' ', 4),
(28, 'Archivada', 'Es el estado que se asigna al accionar el botón archivar', 5, ' ', 4),
(29, 'Eliminada', 'Es el estado que se asigna al eliminar una notificación', 6, ' ', 4);

--
-- Inserting data into table gestiondedocumento_tipodedocumento
--
INSERT INTO gestiondedocumento_tipodedocumento(id, tipo_de_documento, descripcion) VALUES
(4, 'notificacion', 'Modulo de notificaciones');

--
-- Updating data of table mueble_especificaciondemueble
--
UPDATE mueble_especificaciondemueble SET descripcion = 'cama', volumen_en_camion = 15 WHERE id = 1;

--
-- Updating data of table widget_widget
--
UPDATE widget_widget SET numero_de_columna = '1x0' WHERE id = 4;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
