-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.67.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04-03-2016 04:42:54 p.m.
-- Source server version: 5.6.21
-- Source connection string: User Id=root;Host=localhost;Character Set=utf8;
-- Target server version: 5.6.21
-- Target connection string: User Id=root;Host=localhost;Character Set=utf8;
-- Run this script against db_mtvmcotizacionv2 to synchronize it with db_mtvmcotizacionv2
-- Please backup your target database before running this script

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';
USE db_mtvmcotizacionv2;

--
-- Alter table menu_menu
--
ALTER TABLE menu_menu
  DROP FOREIGN KEY menu_menu_menu_padre_id_2e39653d_fk_menu_menu_id;
ALTER TABLE menu_menu
  ADD CONSTRAINT menu_menu_menu_padre_id_2e39653d_fk_menu_menu_id FOREIGN KEY (menu_padre_id)
    REFERENCES menu_menu(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table trabajador_cargotrabajador
--
ALTER TABLE trabajador_cargotrabajador
  DROP FOREIGN KEY trabaja_cargo_padre_id_2378121d_fk_trabajador_cargotrabajador_id;
ALTER TABLE trabajador_cargotrabajador
  ADD CONSTRAINT trabaja_cargo_padre_id_2378121d_fk_trabajador_cargotrabajador_id FOREIGN KEY (cargo_padre_id)
    REFERENCES trabajador_cargotrabajador(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Create table widget_widget
--
CREATE TABLE widget_widget (
  id INT(11) NOT NULL AUTO_INCREMENT,
  usuario_id INT(11) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  visible TINYINT(1) NOT NULL,
  desplegable INT(11) NOT NULL,
  numero_de_columna VARCHAR(100) NOT NULL,
  color VARCHAR(100) NOT NULL,
  orden INT(11) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX usuario_id (usuario_id, nombre),
  CONSTRAINT widget_widget_usuario_id_165f0770_fk_auth_user_id FOREIGN KEY (usuario_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Alter table direccion_edificacion
--
ALTER TABLE direccion_edificacion
  CHANGE COLUMN cantidad_de_pisos cantidad_de_pisos INT(11) DEFAULT NULL,
  CHANGE COLUMN cantidad_de_inmuebles_por_piso cantidad_de_inmuebles_por_piso INT(11) DEFAULT NULL,
  CHANGE COLUMN total_inmuebles total_inmuebles INT(11) DEFAULT NULL,
  CHANGE COLUMN distancia_del_vehiculo distancia_del_vehiculo INT(11) DEFAULT NULL;

--
-- Alter table direccion_inmueble
--
ALTER TABLE direccion_inmueble
  CHANGE COLUMN numero_de_pisos numero_de_pisos INT(11) DEFAULT NULL,
  CHANGE COLUMN total_m2 total_m2 DECIMAL(7, 2) DEFAULT NULL,
  CHANGE COLUMN volumen_baulera volumen_baulera DECIMAL(8, 3) DEFAULT NULL;

--
-- Alter table cliente_clientedireccion
--
ALTER TABLE cliente_clientedireccion
  ADD COLUMN edificacion_id INT(11) DEFAULT NULL AFTER titulo_de_direccion,
  ADD COLUMN inmueble_id INT(11) DEFAULT NULL AFTER edificacion_id;

ALTER TABLE cliente_clientedireccion
  ADD INDEX cliente_clientedireccion_1b0d6425 (edificacion_id);

ALTER TABLE cliente_clientedireccion
  ADD INDEX cliente_clientedireccion_9846f97f (inmueble_id);

ALTER TABLE cliente_clientedireccion
  ADD CONSTRAINT cliente_clie_edificacion_id_3fdfea0c_fk_direccion_edificacion_id FOREIGN KEY (edificacion_id)
    REFERENCES direccion_edificacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cliente_clientedireccion
  ADD CONSTRAINT cliente_clientedire_inmueble_id_770c355_fk_direccion_inmueble_id FOREIGN KEY (inmueble_id)
    REFERENCES direccion_inmueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

INSERT INTO auth_permission(id, name, content_type_id, codename) VALUES
(265, 'Can add Widget', 89, 'add_widget'),
(266, 'Can change Widget', 89, 'change_widget'),
(267, 'Can delete Widget', 89, 'delete_widget');

INSERT INTO django_content_type(id, app_label, model) VALUES
(89, 'widget', 'widget');

UPDATE django_migrations SET applied = '2016-02-04 19:20:53' WHERE id = 25;
UPDATE django_migrations SET applied = '2016-02-04 19:23:15' WHERE id = 26;
UPDATE django_migrations SET applied = '2016-02-12 13:41:18' WHERE id = 27;
UPDATE django_migrations SET applied = '2016-02-15 19:30:54' WHERE id = 28;
UPDATE django_migrations SET applied = '2016-02-15 19:30:59' WHERE id = 29;
UPDATE django_migrations SET applied = '2016-02-15 19:31:17' WHERE id = 30;
UPDATE django_migrations SET applied = '2016-02-15 19:31:23' WHERE id = 31;
UPDATE django_migrations SET applied = '2016-02-15 19:31:32' WHERE id = 32;
UPDATE django_migrations SET applied = '2016-02-15 19:31:49' WHERE id = 33;
UPDATE django_migrations SET applied = '2016-02-17 19:29:15' WHERE id = 34;
UPDATE django_migrations SET applied = '2016-02-17 19:29:20' WHERE id = 35;
UPDATE django_migrations SET applied = '2016-03-01 12:58:37' WHERE id = 36;
UPDATE django_migrations SET applied = '2016-03-01 12:58:38' WHERE id = 37;
UPDATE django_migrations SET applied = '2016-03-01 12:58:38' WHERE id = 38;
UPDATE django_migrations SET applied = '2016-03-01 21:04:28' WHERE id = 39;
UPDATE django_migrations SET applied = '2016-03-01 21:04:31' WHERE id = 40;
UPDATE django_migrations SET applied = '2016-03-02 18:05:31' WHERE id = 41;
UPDATE django_migrations SET applied = '2016-03-02 18:05:32' WHERE id = 42;

INSERT INTO django_migrations(id, app, name, applied) VALUES
(43, 'direccion', '0003_auto_20160303_1401', '2016-03-03 18:31:53'),
(44, 'cliente', '0004_auto_20160303_1401', '2016-03-03 18:31:59'),
(45, 'direccion', '0004_auto_20160303_1403', '2016-03-03 18:33:16'),
(46, 'direccion', '0005_auto_20160304_1558', '2016-03-04 20:32:37');

-- cambios nuevos --

ALTER TABLE widget_widget
  DROP COLUMN desplegable,
  DROP FOREIGN KEY widget_widget_usuario_id_165f0770_fk_auth_user_id,
  DROP INDEX usuario_id,
  CHANGE COLUMN nombre nombre VARCHAR(100) NOT NULL AFTER id,
  CHANGE COLUMN usuario_id usuario_id INT(11) NOT NULL AFTER orden;

ALTER TABLE widget_widget
  ADD UNIQUE INDEX widget_widget_usuario_id_37ef8023_uniq (usuario_id, nombre);

ALTER TABLE widget_widget
  ADD CONSTRAINT widget_widget_usuario_id_1d62947a_fk_auth_user_id FOREIGN KEY (usuario_id)
    REFERENCES auth_user(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Alter table cliente_clientedireccion
--
ALTER TABLE cliente_clientedireccion
  DROP FOREIGN KEY cliente_clie_edificacion_id_3fdfea0c_fk_direccion_edificacion_id;
ALTER TABLE cliente_clientedireccion
  ADD CONSTRAINT cliente_clie_edificacion_id_3fdfea0c_fk_direccion_edificacion_id FOREIGN KEY (edificacion_id)
    REFERENCES direccion_edificacion(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE cliente_clientedireccion
  DROP FOREIGN KEY cliente_clientedire_inmueble_id_770c355_fk_direccion_inmueble_id;
ALTER TABLE cliente_clientedireccion
  ADD CONSTRAINT cliente_clientedire_inmueble_id_770c355_fk_direccion_inmueble_id FOREIGN KEY (inmueble_id)
    REFERENCES direccion_inmueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT;


UPDATE django_migrations SET applied = '2016-02-04 19:20:53' WHERE id = 25;
UPDATE django_migrations SET applied = '2016-02-04 19:23:15' WHERE id = 26;
UPDATE django_migrations SET applied = '2016-02-12 13:41:18' WHERE id = 27;
UPDATE django_migrations SET applied = '2016-02-15 19:30:54' WHERE id = 28;
UPDATE django_migrations SET applied = '2016-02-15 19:30:59' WHERE id = 29;
UPDATE django_migrations SET applied = '2016-02-15 19:31:17' WHERE id = 30;
UPDATE django_migrations SET applied = '2016-02-15 19:31:23' WHERE id = 31;
UPDATE django_migrations SET applied = '2016-02-15 19:31:32' WHERE id = 32;
UPDATE django_migrations SET applied = '2016-02-15 19:31:49' WHERE id = 33;
UPDATE django_migrations SET applied = '2016-02-17 19:29:15' WHERE id = 34;
UPDATE django_migrations SET applied = '2016-02-17 19:29:20' WHERE id = 35;
UPDATE django_migrations SET applied = '2016-03-01 12:58:37' WHERE id = 36;
UPDATE django_migrations SET applied = '2016-03-01 12:58:38' WHERE id = 37;
UPDATE django_migrations SET applied = '2016-03-01 12:58:38' WHERE id = 38;
UPDATE django_migrations SET applied = '2016-03-01 21:04:28' WHERE id = 39;
UPDATE django_migrations SET applied = '2016-03-01 21:04:31' WHERE id = 40;
UPDATE django_migrations SET applied = '2016-03-02 18:05:31' WHERE id = 41;
UPDATE django_migrations SET applied = '2016-03-02 18:05:32' WHERE id = 42;
UPDATE django_migrations SET applied = '2016-03-03 18:31:53' WHERE id = 43;
UPDATE django_migrations SET applied = '2016-03-03 18:31:59' WHERE id = 44;
UPDATE django_migrations SET applied = '2016-03-03 18:33:16' WHERE id = 45;
UPDATE django_migrations SET applied = '2016-03-04 20:32:37' WHERE id = 46;

--
-- Inserting data into table django_migrations
--
INSERT INTO django_migrations(id, app, name, applied) VALUES
(47, 'widget', '0001_initial', '2016-03-14 19:29:32'),
(48, 'widget', '0002_remove_widget_desplegable', '2016-03-14 19:33:38');

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
