-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.67.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25-01-2016 02:32:12 p.m.
-- Source server version: 5.6.21
-- Source connection string: User Id=root;Host=localhost;Character Set=utf8;
-- Target server version: 5.6.21
-- Target connection string: User Id=root;Host=localhost;Character Set=utf8;
-- Run this script against db_mtvmcotizacionv2_prd to synchronize it with db_mtvmcotizacionv2
-- Please backup your target database before running this script

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

SET NAMES 'utf8';
USE db_mtvmcotizacionv2_prd;

--
-- Create table mueble_mueble
--
CREATE TABLE mueble_mueble (
  id INT(11) NOT NULL AUTO_INCREMENT,
  mueble VARCHAR(100) NOT NULL,
  descripcion LONGTEXT NOT NULL,
  trasladable TINYINT(1) NOT NULL,
  tipo_de_mueble_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX mueble (mueble),
  INDEX mueble_mueb_tipo_de_mueble_id_7e72d3b4_fk_mueble_tipodemueble_id (tipo_de_mueble_id),
  CONSTRAINT mueble_mueb_tipo_de_mueble_id_7e72d3b4_fk_mueble_tipodemueble_id FOREIGN KEY (tipo_de_mueble_id)
    REFERENCES mueble_tipodemueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Create table ambiente_ambienteportipodeinmueble
--
CREATE TABLE ambiente_ambienteportipodeinmueble (
  id INT(11) NOT NULL AUTO_INCREMENT,
  predeterminado TINYINT(1) NOT NULL,
  ambiente_id INT(11) NOT NULL,
  especificacion_de_inmueble_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  INDEX ambiente_ambientepo_ambiente_id_73ad5624_fk_ambiente_ambiente_id (ambiente_id),
  INDEX c804ffca241dc6a8ea55ea4144c7a00c (especificacion_de_inmueble_id),
  CONSTRAINT ambiente_ambientepo_ambiente_id_73ad5624_fk_ambiente_ambiente_id FOREIGN KEY (ambiente_id)
    REFERENCES ambiente_ambiente(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT c804ffca241dc6a8ea55ea4144c7a00c FOREIGN KEY (especificacion_de_inmueble_id)
    REFERENCES direccion_especificaciondeinmueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Create table mueble_especificaciondemueble
--
CREATE TABLE mueble_especificaciondemueble (
  id INT(11) NOT NULL AUTO_INCREMENT,
  especificacion_de_mueble VARCHAR(100) NOT NULL,
  descripcion LONGTEXT NOT NULL,
  ancho DECIMAL(7, 2) NOT NULL,
  largo DECIMAL(7, 2) NOT NULL,
  alto DECIMAL(7, 2) NOT NULL,
  volumen_en_camion INT(11) NOT NULL,
  predefinido TINYINT(1) NOT NULL,
  mueble_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  INDEX mueble_especificaciondemueble_49933347 (mueble_id),
  CONSTRAINT mueble_especificaciondemu_mueble_id_771e6d97_fk_mueble_mueble_id FOREIGN KEY (mueble_id)
    REFERENCES mueble_mueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Create table mueble_muebleporambiente
--
CREATE TABLE mueble_muebleporambiente (
  id INT(11) NOT NULL AUTO_INCREMENT,
  predefinido TINYINT(1) NOT NULL,
  ambiente_por_tipo_de_inmueble_id INT(11) NOT NULL,
  especificacion_de_mueble_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  INDEX b9f138942889768994a59045f2fadb23 (especificacion_de_mueble_id),
  INDEX D949a3fd63be7f5d7af8532da369314e (ambiente_por_tipo_de_inmueble_id),
  CONSTRAINT b9f138942889768994a59045f2fadb23 FOREIGN KEY (especificacion_de_mueble_id)
    REFERENCES mueble_especificaciondemueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT D949a3fd63be7f5d7af8532da369314e FOREIGN KEY (ambiente_por_tipo_de_inmueble_id)
    REFERENCES ambiente_ambienteportipodeinmueble(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
